_wandb:
    value:
        cli_version: 0.23.1
        e:
            k990pzk6nhput7t70bc6ri78c3u92jes:
                codePath: c:\Users\aryan\OneDrive\Desktop\DM Lab\AI for Chemistry\Week_3-Deep_learning\Intro_to_DL.ipynb
                codePathLocal: Intro_to_DL.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "511030849536"
                        used: "413707513856"
                email: aryan.cshah1408@gmail.com
                executable: c:\Users\aryan\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: fece39f4a3381cfd30667992cf6755b8aa4a6007
                    remote: https://github.com/Accayo14/AI-for-Chemistry.git
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-0decc06c-0ce2-8548-a0ef-3b9d63a8a66d
                host: Aryan
                memory:
                    total: "16415322112"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\aryan\OneDrive\Desktop\DM Lab\AI for Chemistry\Week_3-Deep_learning\Intro_to_DL.ipynb
                python: CPython 3.13.5
                root: c:\Users\aryan\OneDrive\Desktop\DM Lab\AI for Chemistry\Week_3-Deep_learning
                startedAt: "2025-12-04T10:43:04.548105Z"
                writerId: k990pzk6nhput7t70bc6ri78c3u92jes
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 2
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 1
                - 2
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
hidden_size:
    value: 512
learning_rate:
    value: 0.0005
max_epochs:
    value: 500
